apiVersion: v1
kind: Service
metadata:
  name: demo-service-stable
  labels:
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/instance: stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/instance: stable
  ports:
    - name: http
      port: 80
      targetPort: http
